{% set version = "1.1.3.20260408" %}

package:
  name: types-geopandas
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-geopandas/types_geopandas-{{ version }}.tar.gz
  sha256: 58fc0f8b7b1ce635cd59806d6f46a4f4c92bc7615b0f8fa5fc1a3018f7361779

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >={{ python_min }}
    - types-shapely
    - numpy >=1.20
    - pandas-stubs
    - pyproj

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for geopandas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - p-vdp
