{% set version = "1.1.4.20260807" %}

package:
  name: types-geopandas
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-geopandas/types_geopandas-{{ version }}.tar.gz
  sha256: e7cbf93306473421ba7da82481124a96a81ac219acf6c5381d701f2508d27358

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >={{ python_min }}
    - types-shapely
    - numpy >=1.20
    - pandas-stubs
    - pyproj

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for geopandas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - p-vdp
